INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (101, 'Y', 'john@gmail.com', 'John', 79797979);

INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (102, 'Y', 'smith@gmail.com', 'Smith', 79797979);

INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (103, 'Y', 'Charles@gmail.com', 'charles', 79797979);

INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (104, 'Y', 'Ram@gmail.com', 'Ram', 79797979);

INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (105, 'Y', 'lakshman@gmail.com', 'Lakshman', 79797979);

INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (106, 'Y', 'Bharat@gmail.com', 'Bharat', 79797979);

INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (107, 'Y', 'Sita@gmail.com', 'Sita', 79797979);

INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (108, 'Y', 'Gita@gmail.com', 'Gita', 79797979);

INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (109, 'Y', 'Rani@gmail.com', 'Rani', 79797979);

INSERT INTO CONTACT_DTLS(CONTACT_ID, ACTIVE_SW, CONTACT_EMAIL, CONTACT_NAME, CONTACT_NUMBER)
VALUES (110, 'Y', 'Ching@gmail.com', 'Ching Chong', 79797979);